version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: house-postgres
    environment:
      POSTGRES_DB: house_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - house-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: house-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - house-network
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: house-adminer
    ports:
      - "8080:8080"
    networks:
      - house-network
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  house-network:
    driver: bridge